# --- Petal parameters -----------------------------------------------------------------------------

# Number of petals.  Note that this must be a multiple of 4 due to how I pack 4 petal indices into
# each location in a uniform buffer array that gets passed to the GPU.  This packing allows me to
# render 4x more petals than I otherwise would be able to without packing, and is necessary due to
# the 16 byte alignment constraint and size constraint of uniform buffers.  My GPU has a max uniform
# size of 65536 bytes, which allows me to set n_petals to a maximum value of 16384.  Using
# additional uniform buffers or a different type of buffer would also allow more, but would
# complicate things.
n_petals = 7000
# Range for scale factor randomly selected for each petal.
min_scale = 1.0
max_scale = 2.0

# Petals are rendered with a 3x3 grid of vertices defined in the x/y plane.  The petal bend offsets
# move each of those vertices up or down in the z direction so that the vertices are not perfectly
# coplanar.  This improves how the petals look when they are viewed edge-on by the camera, as they
# are no longer perfectly flat.
#Scale factor for petal bend offsets (applied to all offsets).
petal_bend_vertex_offset_multiplier = 0.1
# Petal bend offsets for each of the 9 vertices used to render the petals, listed in row-major
# order (top-left vertex first, top-middle second, and so forth).
petal_bend_vertex_offsets = [1.0, 0.2, -0.6, -0.1, 0.0, -0.2, -1.0, 0.3, 0.7]

# --- Camera parameters ----------------------------------------------------------------------------

# Location of the near clipping plane of the view frustum (relative to the camera).
camera_near = 1.0
# Location of the far clipping plane of the view frustum (relative to the camera).
camera_far = 100.0
# Vertical field of view (in degrees) of the camera.
camera_fov_y = 60.0

# --- Simulation volume ----------------------------------------------------------------------------

# Define the size of the volume (rectangular prism) in which the petals will move around.  Note that
# these max values all go in both the positive and negative directions, so the actual dimensions of
# the volume will be double these.  These default values have been selected so that the view frustum
# will be completely contained within the volume when the camera is located at its default location
# of (0, 0, -max_z) and facing in the +z direction.
max_x = 110.0
max_y = 65.0
max_z = 50.0

# --- Camera movement ------------------------------------------------------------------------------

# Speed of camera movement when keyboard keys are pressed.  The keyboard controls are similar to
# most first-person shooter games:
#   w -- forward
#   s -- backward
#   a -- left
#   d -- right
#   <spacebar> -- up
#   c -- down
player_movement_speed = 0.5
# Turn speed / sensitivity for mouse control of the camera pitch and yaw angles.  Note that mouse
# camera movement is disabled by default when the program starts.  Right clicking will toggle it on
# and off (capturing and releasing the mouse).
player_turn_speed = 0.1

# --- Petal movement -------------------------------------------------------------------------------
# The petals have both translational and rotational movement.  The rotational movement for each
# petal is randomly chosen at the start of the program and is constant from then on.  The
# translational petal movement is defined by a constant fall speed (subtracted from their y position
# each frame) and movement speed along all 3 axes (X/Y/Z) that changes over time as defined by
# random mixtures of sinusoids.  Petals that would exit the simultation volume (e.g. an x coordinate
# outside of the range [-max_x, max_x]) are wrapped around to the opposite side, thus always keeping
# all petals within the simulation volume.

# Constant fall speed added to the velocity of each petal.
fall_speed = 0.1
# The period (in seconds) of the sinusoids, relative to their frequencies.  So, the frequency 1
# sinusoid will go through 1 cycle in this amount of time, the frequency 2 sinusoid will go through
# 2 cycles in this amount of time, and so forth.
movement_period = 900
# The number of frequencies that will be mixed together to generate each mixture of sinusoids.  This
# also serves as a frequency cap (in conjunction with the movement_period) for how quickly the
# movement can change.
movement_n_frequencies = 60
# These determine the maximum amplitude that can be chosen at each frequency when generating the
# individual sinusoids that are mixed together.  Similar to fractal noise, it is generally good to
# use lower max amplitudes for higher frequencies.  In this case, the max amplitude can be set for
# the lowest and highest frequencies, and will be linearly interpolated for the frequencies in
# between.
movement_high_freq_max_amplitude = 0.015
movement_low_freq_max_amplitude = 0.075
# Defines the range of rotation speeds that can be randomly chosen for each petal at the start of
# the program.
min_rotation_speed = 1.0
max_rotation_speed = 3.0

# --- Rendering to video ---------------------------------------------------------------------------

# Enables or disables rendering to video.  Note that rendering to video assumes that ffmpeg is
# installed and is available on your PATH in your OS command-line.  If it is not, then enabling this
# will cause the program to crash when it cannot find ffmpeg and use it to encode the rendered
# frames to a video file.  Also note that enabling video export will probably cause the program to
# run much slower and be a little choppy.  This is because it renders everything a second time into
# an off-screen buffer, pipes that data to an ffmpeg process, and has to wait for ffmpeg to catch up
# with encoding/compressing the frames before continuing to render more frames.  However, the
# rendered video will not be choppy and should play at the specified rate.
enable_ffmpeg_video_export = false
# Name of the file the video will be exported to.  WARNING: If a file with this name already exists,
# it will get overwritten without prompt if the program is run with video export enabled.
video_export_file = "falling_petals.mp4"
# Frame rate of exported video.  Note that this does not affect the simulation or how the frames are
# rendered.  So if you want to double the FPS of the video without also doubling the perceived speed
# of the petal motion, you'll need to adjust all the petal movement parameters to counteract that
# doubling in playback speed.
video_export_fps = 30
# Resolution of the exported video.
video_export_width = 1920
video_export_height = 1080

# --- Texture parameters ---------------------------------------------------------------------------

[[petal_textures]]
file = "falling_petals/res/PetalsArranged.png"
# Width of a "standard" petal in this texture file, used to scale the petals in this file relative
# to the petals in other texture files.  Since most petals were about 4 grid spaces or 512 pixels
# wide, I set this to 512/8192 = 0.0625.
scale = 0.0625
# Multipliers that can be used to make it easier to enter texture coordinates below when petal
# images are aligned within a grid in the texture file.  Set these to 1 if no scaling is desired.
# For PetalsArranged.png, the petal images are aligned with a grid with cells that are 128x128
# pixels.  Since the texture size is 8192x8192, I use 128/8192 = 0.015625 as the spacing value in
# both the x and y directions.  Then I can enter the coordinate values below as integer indices into
# that grid.
x_multiplier = 0.015625
y_multiplier = 0.015625
# X location, Y location, width, and height (in scaled texture coordinates) of each patch of the
# texture that contains a single petal image.  Texture coordinates are (0.0, 0.0) at the upper left
# corner of the upper left pixel of the texture, and (1.0, 1.0) at the lower right corner of the
# lower right pixel.  These values are scaled (multiplied) by the spacing parameters above to make
# it easier to enter them as values with just a few digits.  Since the spacing parameters above
# have been set appropriately for a 128x128 pixel grid, I can enter these values as integers 
# specifying the grid coordinates and how many grid cells wide/tall each petal image is.
petal_coordinates = [
    # Col 1: 3x1
    [0, 0, 3, 1],
    [0, 1, 3, 1],
    [0, 2, 3, 1],
    [0, 3, 3, 1],
    [0, 4, 3, 1],
    [0, 5, 3, 1],
    # Col 2: 6x3
    [3, 0, 6, 3],
    [3, 3, 6, 3],
    [3, 6, 6, 3],
    [3, 9, 6, 3],
    [3, 12, 6, 3],
    [3, 15, 6, 3],
    [3, 18, 6, 3],
    [3, 21, 6, 3],
    [3, 24, 6, 3],
    [3, 27, 6, 3],
    [3, 30, 6, 3],
    [3, 33, 6, 3],
    [3, 36, 6, 3],
    [3, 39, 6, 3],
    # Col 3: 5x3
    [9, 0, 5, 3],
    [9, 3, 5, 3],
    [9, 6, 5, 3],
    [9, 9, 5, 3],
    [9, 12, 5, 3],
    [9, 15, 5, 3],
    [9, 18, 5, 3],
    [9, 21, 5, 3],
    [9, 24, 5, 3],
    [9, 27, 5, 3],
    [9, 30, 5, 3],
    [9, 33, 5, 3],
    # Col 4: 4x2
    [14, 0, 4, 2],
    [14, 2, 4, 2],
    [14, 4, 4, 2],
    [14, 6, 4, 2],
    [14, 8, 4, 2],
    [14, 10, 4, 2],
    [14, 12, 4, 2],
    [14, 14, 4, 2],
    [14, 16, 4, 2],
    [14, 18, 4, 2],
    [14, 20, 4, 2],
    [14, 22, 4, 2],
    [14, 24, 4, 2],
    [14, 26, 4, 2],
    # Col 5: 5x2
    [18, 0, 5, 2],
    [18, 2, 5, 2],
    [18, 4, 5, 2],
    [18, 6, 5, 2],
    [18, 8, 5, 2],
    [18, 10, 5, 2],
    [18, 12, 5, 2],
    [18, 14, 5, 2],
    [18, 16, 5, 2],
    [18, 18, 5, 2],
    [18, 20, 5, 2],
    [18, 22, 5, 2],
    [18, 24, 5, 2],
    [18, 26, 5, 2],
    [18, 28, 5, 2],
    [18, 30, 5, 2],
    [18, 32, 5, 2],
    [18, 34, 5, 2],
    [18, 36, 5, 2],
    [18, 38, 5, 2],
    [18, 40, 5, 2],
    [18, 42, 5, 2],
    # Col 6: 4x3
    [23, 0, 4, 3],
    [23, 3, 4, 3],
    [23, 6, 4, 3],
    # Col 7: 5x1
    [27, 0, 5, 1],
    [27, 1, 5, 1],
    [27, 2, 5, 1],
    [27, 3, 5, 1],
    [27, 4, 5, 1],
    [27, 5, 5, 1],
    # Col 8: 6x2
    [32, 0, 6, 2],
    [32, 2, 6, 2],
    [32, 4, 6, 2],
    [32, 6, 6, 2],
    [32, 8, 6, 2],
    [32, 10, 6, 2],
    [32, 12, 6, 2],
    [32, 14, 6, 2],
    [32, 16, 6, 2],
    [32, 18, 6, 2],
    # Col 9: 4x1
    [38, 0, 4, 1],
    [38, 1, 4, 1],
    [38, 2, 4, 1],
    [38, 3, 4, 1],
    [38, 4, 4, 1],
    [38, 5, 4, 1],
    [38, 6, 4, 1],
    [38, 7, 4, 1],
    [38, 8, 4, 1],
    [38, 9, 4, 1],
    [38, 10, 4, 1],
    [38, 11, 4, 1],
    [38, 12, 4, 1],
    [38, 13, 4, 1],
    # Col 10: 6x4
    [42, 0, 6, 4],
    # Col 11: 2x1
    [48, 0, 2, 1],
    # Col 12: 3x2
    [50, 0, 3, 2],
    # Col 13: 7x3
    [53, 0, 7, 3],
]

[[petal_textures]]
file = "falling_petals/res/pink_petals_long.png"
scale = 1
x_multiplier = 1
y_multiplier = 1
petal_coordinates = [
    [0.000, 0.021, 0.250, 0.412],
    [0.250, 0.021, 0.250, 0.412],
    [0.500, 0.005, 0.253, 0.445],
    [0.751, 0.001, 0.249, 0.458],
    [0.000, 0.541, 0.251, 0.407],
    [0.250, 0.532, 0.253, 0.423],
    [0.502, 0.488, 0.253, 0.512],
    [0.767, 0.487, 0.216, 0.513],
]

[[petal_textures]]
file = "falling_petals/res/pink_petal.png"
scale = 1
x_multiplier = 1
y_multiplier = 1
petal_coordinates = [
    [0.0, 0.0, 1.0, 1.0],
]

[[petal_textures]]
file = "falling_petals/res/pink_petals_short.png"
scale = 1
x_multiplier = 1
y_multiplier = 1
petal_coordinates = [
    [0.000, 0.000, 0.218, 0.500],
    [0.256, 0.000, 0.223, 0.500],
    [0.506, 0.000, 0.239, 0.500],
    [0.765, 0.000, 0.235, 0.500],
    [0.000, 0.500, 0.218, 0.500],
    [0.256, 0.500, 0.223, 0.500],
    [0.506, 0.500, 0.239, 0.500],
    [0.765, 0.500, 0.235, 0.500],
]

[[petal_textures]]
file = "falling_petals/res/purple_petals.png"
scale = 1
x_multiplier = 1
y_multiplier = 1
petal_coordinates = [
    [0.000, 0.011, 0.250, 0.447],
    [0.250, 0.000, 0.250, 0.455],
    [0.499, 0.022, 0.237, 0.408],
    [0.750, 0.060, 0.250, 0.373],
    [0.000, 0.549, 0.250, 0.451],
    [0.250, 0.551, 0.251, 0.449],
    [0.501, 0.565, 0.251, 0.435],
    [0.751, 0.592, 0.249, 0.381],
]

[[petal_textures]]
file = "falling_petals/res/red_petals.png"
scale = 1
x_multiplier = 1
y_multiplier = 1
petal_coordinates = [
    [0.000, 0.027, 0.317, 0.424],
    [0.328, 0.000, 0.341, 0.465],
    [0.682, 0.023, 0.305, 0.410],
    [0.000, 0.567, 0.315, 0.421],
    [0.346, 0.541, 0.344, 0.459],
    [0.690, 0.504, 0.310, 0.405],
]

[[petal_textures]]
file = "falling_petals/res/rose_petals.png"
scale = 1
x_multiplier = 1
y_multiplier = 1
petal_coordinates = [
    [0.012, 0.032, 0.312, 0.933],
    [0.364, 0.052, 0.284, 0.900],
    [0.686, 0.047, 0.296, 0.896],
]
